wordpress:
  build: .
  links:
    - db
  ports:
    - "80:80"
  environment:
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: admin
    WORDPRESS_DB_PASSWORD: "**ChangeMe**"
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_PORT: 3306
db:
  image: tutum/mysql:5.5
  environment:
    MYSQL_PASS: "**ChangeMe**"
